# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-16 19:03
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('profile_bio', models.TextField()),
                ('profile_contact', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
